module.exports = {
  'admin': ['*'],
  'instruments': [
            "PostToken",
            "PostDigitalWalletValidation",
            "StorefrontGetAccount",
            "StorefrontPatchAccount",
            "StorefrontPostPayment",
            "StorefrontGetTransactionCollection",
            "StorefrontGetTransaction",
            "StorefrontGetPaymentInstrumentCollection",
            "StorefrontPostPaymentInstrument",
            "StorefrontGetPaymentInstrument",
            "StorefrontPatchPaymentInstrument",
            "StorefrontPostPaymentInstrumentDeactivation",
            "StorefrontGetWebsite",
            "StorefrontGetOrderCollection",
            "StorefrontGetOrder",
            "StorefrontPostSubscription",
            "StorefrontGetInvoiceCollection",
            "StorefrontGetInvoice",
            "StorefrontGetProductCollection",
            "StorefrontGetProduct",
            "StorefrontGetPlanCollection",
            "StorefrontGetPlan",
            "StorefrontPostReadyToPay",
            "StorefrontGetPaymentInstrumentSetup",
            "StorefrontPostPaymentInstrumentSetup",
        ]
}